FROM python:3.7.3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install -r requirements.txt

# CMD echo "test" && tail -f /dev/null

WORKDIR /usr/src/app/demo

CMD python manage.py runserver 0.0.0.0:8000