# Generated by Django 2.2.3 on 2019-07-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=20)),
                ('shipping', models.DecimalField(decimal_places=0, max_digits=4)),
                ('created_at', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
    ]
